receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
  zipkin: # ðŸ‘ˆ Necesario para recibir desde Istio
    endpoint: 0.0.0.0:9411

exporters:
  otlphttp:
    endpoint: ${TEMPO_URL}
    headers:
      "X-Scope-OrgID": "single-tenant"
    tls:
      insecure: true
  # logging:
  #   loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      exporters: [otlphttp]
  # telemetry:
  #   logs:
  #     level: debug
